<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RJ84P5M-Anamika" name="IBM_Project_API_Testing.IBM_Project_API_Testing.API_Testing" tests="5" failures="0" timestamp="21 Mar 2022 07:24:25 GMT" time="9.975" errors="1">
  <testcase name="login" time="1.432" classname="IBM_Project_API_Testing.IBM_Project_API_Testing.API_Testing"/>
  <testcase name="createUser" time="5.388" classname="IBM_Project_API_Testing.IBM_Project_API_Testing.API_Testing"/>
  <testcase name="logout" time="1.632" classname="IBM_Project_API_Testing.IBM_Project_API_Testing.API_Testing"/>
  <testcase name="delete" time="0.003" classname="IBM_Project_API_Testing.IBM_Project_API_Testing.API_Testing">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at IBM_Project_API_Testing.IBM_Project_API_Testing.API_Testing.delete(API_Testing.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- delete -->
  <testcase name="modifyUser" time="1.520" classname="IBM_Project_API_Testing.IBM_Project_API_Testing.API_Testing"/>
</testsuite> <!-- IBM_Project_API_Testing.IBM_Project_API_Testing.API_Testing -->
